### ISSUE TITLE
Loading models 

### ISSUE THREAD

**Issue by negara** [JordanSamhi/RAICC#1]
I get java.lang.NullPointerException when running RAICC  as follows:
Exception in thread "main" java.lang.NullPointerException
	at soot.JastAddJ.Program.initPaths(Program.java:350)
	at soot.SootResolver.<init>(SootResolver.java:87)
	at soot.Singletons.soot_SootResolver(Singletons.java:802)
	at soot.SootResolver.v(SootResolver.java:91)
	at soot.Scene.tryLoadClass(Scene.java:670)
	at soot.Scene.loadBasicClasses(Scene.java:1268)
	at soot.Scene.loadNecessaryClasses(Scene.java:1347)
	at edu.psu.cse.siis.ic3.SetupApplication.initializeSoot(SetupApplication.java:343)
	at edu.psu.cse.siis.ic3.SetupApplication.calculateSourcesSinksEntrypoints(SetupApplication.java:124)
	at edu.psu.cse.siis.ic3.Ic3Analysis.initializeAnalysis(Ic3Analysis.java:146)
	at edu.psu.cse.siis.ic3.Ic3Analysis.initializeAnalysis(Ic3Analysis.java:64)
	at edu.psu.cse.siis.coal.Analysis.performAnalysis(Analysis.java:73)
	at lu.uni.trux.raicc.Main.main(Main.java:45)

I suspect there is a problem with loading coal models. Is there anything I should set beside the maven commands in the READ.ME. file?

**Comment by JordanSamhi** [comment]
Dear @negara,

Could you provide the apk you used as input for RAICC and the command line you used?

**Comment by negara** [comment]
Thanks for your quick reply. 
I use the following command:
java -jar target/RAICC-1.0-jar-with-dependencies.jar -a PATH/ICC-Bench-master/apks/IccTargetFinding/icc_explicit1.apk -cp PATH/Android/sdk/platforms -model src/main/resources/models/

I tried running RAICC with different APK files from ICC-bench, just to get it working.
The APK for the command above can be found here:
https://github.com/fgwei/ICC-Bench/tree/master/apks/IccTargetFinding

**Comment by JordanSamhi** [comment]
I was able to reproduce the error you get, the solution is simple:
You should use java 8 to execute the command, the reason is that RAICC is based on Soot which needs java 8 to work (at least for the version I used in RAICC).
I tested with java 11 I got the same error as you got.

Could you confirm that you got it working with Java 8?

**Comment by negara** [comment]
The tool itself works fine with Java 8. 
But the problem still exists when I try to build the project as an eclipse project (with Java 8).

**Comment by negara** [comment]
I was able to build the project on eclipse, too. 
I needed to change the JRE version in maven build of pom.xml as well. 

Thanks for the help :)
