### ISSUE TITLE
Error While analyzing real world apps

### ISSUE THREAD

**Issue by negara** [JordanSamhi/RAICC#2]
While RAICC works fine on the benchmarks in the repository, I keep getting one of these two errors when I run it on real world apps:
Could you please let me know why this happens?
I attached one of the problematic apps. 
[com.lifeteen.events-1.0.4.zip](https://github.com/JordanSamhi/RAICC/files/6291446/com.lifeteen.events-1.0.4.zip)

Exception in thread "main" java.util.NoSuchElementException: HashChain.LinkIterator.next() reached end of chain without reaching specified tail unit
	at soot.util.HashChain$LinkIterator.next(HashChain.java:508)
	at soot.PatchingChain$PatchingIterator.next(PatchingChain.java:239)
	at soot.PatchingChain$PatchingIterator.next(PatchingChain.java:1)
	at soot.toolkits.graph.ExceptionalUnitGraph.buildExceptionDests(ExceptionalUnitGraph.java:348)
	at soot.toolkits.graph.ExceptionalUnitGraph.initialize(ExceptionalUnitGraph.java:274)
	at soot.toolkits.graph.ExceptionalUnitGraph.<init>(ExceptionalUnitGraph.java:159)
	at soot.dexpler.TrapMinimizer.internalTransform(TrapMinimizer.java:59)
	at soot.BodyTransformer.transform(BodyTransformer.java:51)
	at soot.BodyTransformer.transform(BodyTransformer.java:58)
	at soot.BodyTransformer.transform(BodyTransformer.java:63)
	at soot.dexpler.DexBody.jimplify(DexBody.java:633)
	at soot.dexpler.DexMethod$1.getBody(DexMethod.java:150)
	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:322)
	at soot.PackManager.retrieveAllBodies(PackManager.java:1158)
	at soot.PackManager.runPacksNormally(PackManager.java:459)
	at soot.PackManager.runPacks(PackManager.java:392)
	at lu.uni.preprocessIntentSender.ISPreprocessor.run(ISPreprocessor.java:88)
	at lu.uni.trux.raicc.Main.main(Main.java:45)

Exception in thread "main" java.lang.RuntimeException: Exception reference used other than as the first statement of an exception handler.
	at soot.jimple.toolkits.typing.fast.AugEvalFunction.eval_(AugEvalFunction.java:159)
	at soot.jimple.toolkits.typing.fast.AugEvalFunction.eval(AugEvalFunction.java:41)
	at soot.jimple.toolkits.typing.fast.TypeResolver.applyAssignmentConstraints(TypeResolver.java:480)
	at soot.jimple.toolkits.typing.fast.TypeResolver.inferTypes(TypeResolver.java:150)
	at soot.jimple.toolkits.typing.TypeAssigner.internalTransform(TypeAssigner.java:132)
	at soot.BodyTransformer.transform(BodyTransformer.java:51)
	at soot.BodyTransformer.transform(BodyTransformer.java:58)
	at soot.BodyTransformer.transform(BodyTransformer.java:63)
	at soot.dexpler.DexBody.jimplify(DexBody.java:550)
	at soot.dexpler.DexMethod$1.getBody(DexMethod.java:150)
	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:322)
	at soot.PackManager.retrieveAllBodies(PackManager.java:1158)
	at soot.PackManager.runPacksNormally(PackManager.java:459)
	at soot.PackManager.runPacks(PackManager.java:392)
	at lu.uni.preprocessIntentSender.ISPreprocessor.run(ISPreprocessor.java:88)
	at lu.uni.trux.raicc.Main.main(Main.java:45)

**Comment by JordanSamhi** [comment]
Hello @negara,

I was not able to reproduce the error you have, I downloaded RAICC, installed it with the default configuration and I run it.
I received no error, the APK was analyzed just fine.
Do you confirm you still have the error ?

Can you share the command line you used ?
Did you use Java 8 ?

I have attached the ouput I got with you apk :
[output.txt](https://github.com/JordanSamhi/RAICC/files/6337512/output.txt)
