### ISSUE TITLE
Error While analyzing real world apps

### ISSUE THREAD

**Issue by sunxiaobiu** [JordanSamhi/RAICC#5]
Hi Jordan, I am currently trying to use RAICC to construct inter-component CGs. RAICC works fine on Benchmarks but throws exceptions on real-world apps. The error message and the apk are attached as follows. 

`
Warning: javax.net.ssl.TrustManager is a phantom class!
array element type (narr range): java.lang.String
array element type: (filled narr)java.lang.String
array element type: (filled narr)java.lang.String
array element type: (filled narr)java.lang.String
array element type: (filled narr)java.lang.String
array element type (narr range): java.lang.String
array element type: (filled narr)java.lang.String
array element type: (filled narr)java.lang.String
array element type: (filled narr)java.lang.String
array element type: (filled narr)java.lang.String
Exception in thread "main" java.util.NoSuchElementException: HashChain.LinkIterator.next() reached end of chain without reaching specified tail unit
	at soot.util.HashChain$LinkIterator.next(HashChain.java:508)
	at soot.PatchingChain$PatchingIterator.next(PatchingChain.java:239)
	at soot.PatchingChain$PatchingIterator.next(PatchingChain.java:1)
	at soot.toolkits.graph.ExceptionalUnitGraph.buildExceptionDests(ExceptionalUnitGraph.java:348)
	at soot.toolkits.graph.ExceptionalUnitGraph.initialize(ExceptionalUnitGraph.java:274)
	at soot.toolkits.graph.ExceptionalUnitGraph.<init>(ExceptionalUnitGraph.java:159)
	at soot.dexpler.TrapMinimizer.internalTransform(TrapMinimizer.java:59)
	at soot.BodyTransformer.transform(BodyTransformer.java:51)
	at soot.BodyTransformer.transform(BodyTransformer.java:58)
	at soot.BodyTransformer.transform(BodyTransformer.java:63)
	at soot.dexpler.DexBody.jimplify(DexBody.java:633)
	at soot.dexpler.DexMethod$1.getBody(DexMethod.java:150)
	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:322)
	at soot.PackManager.retrieveAllBodies(PackManager.java:1158)
	at soot.PackManager.runPacksNormally(PackManager.java:459)
	at soot.PackManager.runPacks(PackManager.java:392)
	at lu.uni.preprocessIntentSender.ISPreprocessor.run(ISPreprocessor.java:88)
	at lu.uni.trux.raicc.Main.main(Main.java:45)
`

apk: https://zenodo.org/record/6777613#.Yrv07exBxr0

b.t.w how can I get inter-component CGs from RAICC?

**Comment by JordanSamhi** [comment]
Hi @sunxiaobiu,

I have reproduced your problem and can confirm that this is not a problem inherent to RAICC, rather it seems to lie in Soot directly or in Soot's DEXPLER module which transforms the Dalvik bytecode into Jimple. However, I am not sure what caused the problem.

For your second question about the inter-component call graph, you will not be able to get it with RAICC.
Indeed, RAICC instruments a given app to transform Atypical ICC into standard ICC, so that other tools (e.g., IccTA) can process it and perform ICC analysis. So to get the inter-component CG, I would recommend the following procedure:
1. Execute RAICC to instrument a given apk
2. Load the instrumented apk with IccTA (https://github.com/lilicoding/soot-infoflow-android-iccta) with which you can extract the new inter-component CG generated

In fact, at some point, RAICC should be integrated into IccTA.

**Comment by sunxiaobiu** [comment]
Many thanks for your quick response and solution! Save my day.
